/** All 25 departments of Peru with default shipping costs in soles */
export const PERU_DEPARTMENTS = [
  'Amazonas',
  'Áncash',
  'Apurímac',
  'Arequipa',
  'Ayacucho',
  'Cajamarca',
  'Callao',
  'Cusco',
  'Huancavelica',
  'Huánuco',
  'Ica',
  'Junín',
  'La Libertad',
  'Lambayeque',
  'Lima',
  'Loreto',
  'Madre de Dios',
  'Moquegua',
  'Pasco',
  'Piura',
  'Puno',
  'San Martín',
  'Tacna',
  'Tumbes',
  'Ucayali',
] as const;

export type PeruDepartment = (typeof PERU_DEPARTMENTS)[number];

/** Default shipping rates — admin can override from /admin/envios */
export const DEFAULT_SHIPPING_RATES: Record<PeruDepartment, number> = {
  Lima: 0,
  Callao: 5,
  Ica: 15,
  'La Libertad': 20,
  Lambayeque: 20,
  Arequipa: 30,
  Piura: 30,
  Junín: 30,
  Áncash: 30,
  Cusco: 35,
  Puno: 35,
  Tacna: 35,
  Moquegua: 35,
  Ayacucho: 40,
  Huancavelica: 40,
  Apurímac: 40,
  Cajamarca: 40,
  Huánuco: 40,
  Pasco: 40,
  'San Martín': 45,
  Amazonas: 50,
  Tumbes: 50,
  Loreto: 60,
  'Madre de Dios': 60,
  Ucayali: 60,
};
